### ISSUE TITLE
Users unable to execute commands.

### ISSUE THREAD

**Issue by SessionExpired** [Pradoxzon/EcoModIssues#4]
Having an odd issue with basic users who join the server get kicked with an Exception error when running commands. (/users, /authlevel, etc..)

Caught exception

<size=60.00%>Exception has been thrown by the target of an invocation.
Input string was not in a correct format.

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eco.Gameplay.Systems.Chat.ChatManager.InvokeCommand(String commandName, MethodInfo method, String args, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.ProcessAsCommand(String text, User user)
   at Eco.Gameplay.Systems.Chat.ChatManager.SendChat(ChatMessage msg, String text, User user)
</size>

Admin also gets this issue when running some commands
(/perm-reload)

**Comment by Pradoxzon** [comment]
I'm sorry for not looking more into this sooner.

I am updating my mods for Eco 0.8.0.1, and am fixing some other issues with GroupManager that have developed. If there are still issues or exceptions being thrown when the new version of GroupManager is released please let me know.
